# CIFuzz job based on https://google.github.io/oss-fuzz/getting-started/continuous-integration/
name: Reusable CIFuzz

on:
  workflow_call:
    inputs:
      oss-fuzz-project-name:
        description: OSS-Fuzz project name
        required: true
        type: string
      sanitizer:
        description: OSS-Fuzz sanitizer
        required: true
        type: string

permissions: {}

jobs:
  cifuzz:
    name: ${{ inputs.oss-fuzz-project-name }} (${{ inputs.sanitizer }})
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Build fuzzers (${{ inputs.sanitizer }})
        id: build
        uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@a068ebf54a1caecb36a7fae35db217ba7e0d93b6 # master
        with:
          oss-fuzz-project-name: ${{ inputs.oss-fuzz-project-name }}
          sanitizer: ${{ inputs.sanitizer }}
      - name: Run fuzzers (${{ inputs.sanitizer }})
        uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@a068ebf54a1caecb36a7fae35db217ba7e0d93b6 # master
        with:
          fuzz-seconds: 600
          oss-fuzz-project-name: ${{ inputs.oss-fuzz-project-name }}
          output-sarif: true
          sanitizer: ${{ inputs.sanitizer }}
      - name: Upload crash
        if: failure() && steps.build.outcome == 'success'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ inputs.sanitizer }}-artifacts
          path: ./out/artifacts
      - name: Upload SARIF
        if: always() && steps.build.outcome == 'success'
        uses: github/codeql-action/upload-sarif@7211b7c8077ea37d8641b6271f6a365a22a5fbfa # v4.36.0
        with:
          sarif_file: cifuzz-sarif/results.sarif
          checkout_path: cifuzz-sarif
