name: Mark stale pull requests

on:
  schedule:
  - cron: "0 */6 * * *"

permissions: {}

jobs:
  stale:
    if: github.repository_owner == 'python'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    timeout-minutes: 10

    steps:
    - name: "Check PRs"
      uses: actions/stale@eb5cf3af3ac0a1aa4c9c45633dd1ae542a27a899 # v10.3.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-pr-message: 'This PR is stale because it has been open for 30 days with no activity.'
        stale-pr-label: 'stale'
        days-before-issue-stale: -1
        days-before-pr-stale: 30
        days-before-close: -1
        ascending: true
        operations-per-run: 120
